---
- name: start nginx container
  docker_container:
    name: nginx
    image: nginx
    state: started
    restart_policy: unless-stopped
    published_ports:
      - 80:80
  tags:
    - nginx

- name: install httpd-tools
  yum:
    name: httpd-tools
    state: present
  tags:
    - install