all:
  hosts:
    node1:
      ansible_host: 192.168.33.11
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    node2:
      ansible_host: 192.168.33.12
      ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
    # node3:
    #   ansible_host: 192.168.33.13
    #   ansible_ssh_private_key_file: ~/.vagrant.d/insecure_private_key
  children:
    nginx:
      hosts:
        node1:
        node2:
      vars:
        # nginx_config_http_template_enable: true
        nginx_config_http_template:
          - listen: "80"
            server_name: "localhost"
            template_file: etc/nginx/conf.d/gqsp.conf.j2
            filename: gqsp.ccbtrust.com.cn.conf
            # conf_file_name: default.conf
            # conf_file_location: /etc/nginx/conf.d/
            upstream_parameters: |
              upstream abc {
                server 127.0.0.1;
                server 127.0.0.2;
              }

