---
# defaults file for nginx
# nginx install
nginx_version: 1.18.0
nginx_owner: root
nginx_group: root
nginx_conf_path: /etc/nginx/conf.d

# nginx main
nginx_user: nginx
nginx_worker_processes: auto
nginx_worker_connections: "1024"


# nginx_conf_template: "etc/nginx/nginx.conf.j2"
# nginx_vhost_template: "etc/nginx/conf.d/vhost.conf.j2"

# nginx_worker_processes: >-
#  "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"

# nginx_multi_accept: "off"


# nginx_vhosts: []
nginx_config_template:
  - listen: "80"
    server_name: "example.com"
    # server_name_redirect: "www.example.com"
    # root: "/var/www/example.com"
    # index: "index.php index.html index.htm"
    # error_page: ""
    # access_log: ""
    # error_log: ""
    state: "present"
    template: "{{ nginx_vhost_template }}"
    filename: "example.com.conf"
    extra_parameters: |
      location ~ \.php$ {
          fastcgi_split_path_info ^(.+\.php)(/.+)$;
          fastcgi_pass unix:/var/run/php5-fpm.sock;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
      }
      ssl_certificate     /etc/ssl/certs/ssl-cert-snakeoil.pem;
      ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;
      ssl_protocols       TLSv1.1 TLSv1.2;
      ssl_ciphers         HIGH:!aNULL:!MD5;

