---
# tasks file for redis_exporter
- name: Install redis_exporter package
  yum:
    name: "redis_exporter-{{ redis_exporter_version }}"
    state: present

- name: Copy redis_exporter systemd unit file.
  copy:
    src: redis_exporter.service
    dest: /usr/lib/systemd/system/redis_exporter.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart redis_exporter

- name: Enabled and started redis_exporter service
  systemd:
    name: redis_exporter
    state: started
    enabled: yes
    daemon_reload: yes
