---
- name: Stop firewalld
  service: name=firewalld state=stopped enabled=no
  tags:
    - firewalld

- name: Disable SELinux
  selinux:
    policy: targeted
    state: disabled
  when: ansible_selinux.status == "enabled"
  tags:
    - selinux

- name: Check presence of fastestmirror.conf
  stat:
    path: /etc/yum/pluginconf.d/fastestmirror.conf
  register: fastestmirror

# the fastestmirror plugin can actually slow down Ansible deployments
- name: Disable fastestmirror plugin if requested
  lineinfile:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    regexp: "^enabled=.*"
    line: "enabled=0"
    state: present
  become: true
  when:
    - fastestmirror.stat.exists
    - not centos_fastestmirror_enabled

- name: Install epel-release packages
  yum: name=epel-release state=present

- name: Use mirrors for CentOS 7 base repository
  template:
    src: "{{ item }}.j2"
    dest: "/etc/yum.repos.d/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - CentOS-Base.repo
    - epel.repo
  tags:
    - repo

- name: Install common packages for develop and debug
  yum:
    name:
      - vim
      - net-tools
      - wget
      - telnet
    state: present
  tags:
    - develop
    - packages
