---
docker_version: 19.03.9
docker_archive_name: "docker-{{ docker_version }}.tgz"

# Container runtime,
# Supported: docker, nvidia-docker, containerd.
container_runtime: docker

# container runtime paths
docker_data_dir: /var/lib/docker
docker_config_dir: /etc/docker
docker_shim_dir: /var/lib/dockershim

# docker deamon config
registry_mirrors: []
insecure_registries: []

docker_cgroup_driver: "systemd"
docker_storage_driver: overlay2
docker_storage_opts:
  - "overlay2.override_kernel_check=true"
docker_log_driver: json-file
docker_log_opts:
  max-size: "1000m"
  max-file: "3"
  labels: "production_status"
  env: "os,customer"
